/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PL;

import java.awt.Container;
import java.awt.Toolkit;


public class MainFrame extends javax.swing.JFrame {

    
    public static Container c;
    int currentuserid;
    public MainFrame(int currentuserid)
    {
        initComponents();
        this.currentuserid=currentuserid;
        this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        c=this.getContentPane();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menulogout = new javax.swing.JMenu();
        milogout = new javax.swing.JMenuItem();
        miums = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        miP = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menulogout.setText("Logout");

        milogout.setText("LogOut");
        milogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                milogoutActionPerformed(evt);
            }
        });
        menulogout.add(milogout);

        jMenuBar1.add(menulogout);

        miums.setText("UMS");
        miums.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miumsActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Manage Users");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        miums.add(jMenuItem1);

        miP.setText("Manage Profile");
        miP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPActionPerformed(evt);
            }
        });
        miums.add(miP);

        jMenuBar1.add(miums);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
       // System.out.println("sdfghjkl");  
        c.removeAll();
        c.setVisible(false);
        ManageUserPannel mup=new ManageUserPannel();
        mup.setBounds(20,20, 582, 589);
        c.add(mup);
        c.setVisible(true); 
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void milogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_milogoutActionPerformed
        this.dispose();
        new LoginFrame().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_milogoutActionPerformed

    private void miumsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miumsActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_miumsActionPerformed

    private void miPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPActionPerformed
        // TODO add your handling code here:
        c.removeAll();
        c.setVisible(false);
        ManageUserProfilePanel mup=new ManageUserProfilePanel(this.currentuserid);
        mup.setBounds(20,20, 542, 435);
        c.add(mup);
        c.setVisible(true);
        
    }//GEN-LAST:event_miPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menulogout;
    private javax.swing.JMenuItem miP;
    private javax.swing.JMenuItem milogout;
    private javax.swing.JMenu miums;
    // End of variables declaration//GEN-END:variables
}
